# Generated by Django 5.2.17 on 2026-10-01 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0024_orderitem_unit_cost_at_order_and_more'),
        ('userprofile', '0002_userprofile_avg_rating_userprofile_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expenses_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(blank=True, db_index=True, help_text='Human-readable business identifier, e.g. EXP-2026-000001.', max_length=64, null=True)),
                ('title', models.CharField(help_text='Short description of the expense.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary value in PKR / local currency.', max_digits=12)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='The actual date on which the expense occurred.')),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Credit / Debit Card'), (3, 'Bank Transfer'), (4, 'Online / Digital Wallet'), (5, 'Other')], db_index=True, default=1)),
                ('vendor_payee', models.CharField(blank=True, default='', help_text='Recipient, supplier, contractor, or utility authority.', max_length=255)),
                ('reference_number', models.CharField(blank=True, default='', help_text='External invoice number, cheque ref, or transaction ID.', max_length=120)),
                ('notes', models.TextField(blank=True, default='', help_text='Detailed audit notes.')),
                ('receipt', models.FileField(blank=True, help_text='Optional scanned bill, receipt, or invoice.', null=True, upload_to='expense_receipts/')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Voided')], db_index=True, default=1)),
                ('void_reason', models.TextField(blank=True, default='', help_text='Mandatory explanation if voided.')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='userprofile.userprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='restaurants.restaurant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to='userprofile.userprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='expenses_ca_restaur_895567_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_expense_category_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['restaurant', 'expense_date'], name='expenses_restaur_173e92_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['restaurant', 'status'], name='expenses_restaur_7a3ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['restaurant', 'category'], name='expenses_restaur_e4fcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['restaurant', 'payment_method'], name='expenses_restaur_704996_idx'),
        ),
    ]
