# Generated by Django 5.2.9 on 2025-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("manager", "Manager"),
                    ("restaurant_owner", "Restaurant Owner"),
                    ("super_admin", "Super Admin"),
                ],
                default="user",
                max_length=255,
            ),
        ),
    ]
