# Generated by Django 5.2.9 on 2025-12-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_copyright',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
