# Generated by Django 5.0.14 on 2025-12-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reviews', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='waiter',
            field=models.ForeignKey(blank=True, help_text='Assign waiter if dine-in service was provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_reviews', to='userprofile.userprofile'),
        ),
    ]
