# Generated by Django 5.2.9 on 2025-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_review_user_review_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('TO_PREPATRE', 'To Prepare'), ('PREPARING', 'Preparing'), ('PREPARED', 'Prepared'), ('SERVED', 'Served')], default='TO_PREPATRE', max_length=20),
        ),
    ]
