# Generated by Django 5.2.9 on 2025-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_orders_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("TO_PREPARE", "To Prepare"),
                    ("PREPARING", "Preparing"),
                    ("PREPARED", "Prepared"),
                    ("SERVED", "Served"),
                ],
                default="TO_PREPARE",
                max_length=20,
            ),
        ),
    ]
