# Generated by Django 5.2.9 on 2025-12-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_orders_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_state",
            field=models.CharField(
                choices=[
                    ("OCCUPIED", "Table Occupied"),
                    ("SERVED", "Order Served"),
                    ("EMPTY", "Table Empty"),
                    ("PREPARING", "Order Preparing"),
                    ("READY", "Order Ready"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
    ]
