# Generated by Django 5.2.9 on 2025-12-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_table_table_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_state",
            field=models.CharField(
                choices=[
                    ("EMPTY", "Empty"),
                    ("RESERVED", "Reserved"),
                    ("OCCUPIED", "Occupied"),
                    ("ORDER_PLACED", "Order Placed"),
                    ("PREPARING", "Preparing Order"),
                    ("READY", "Ready to Serve"),
                    ("SERVED", "Served"),
                    ("PAYMENT_PENDING", "Awaiting Payment"),
                    ("CLEANING", "Cleaning"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
    ]
