# Generated by Django 5.2.9 on 2025-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_orders_payment_status_menuitem_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
