# Generated by Django 5.2.9 on 2025-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_table_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymet_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
