# Generated by Django 5.2.9 on 2025-12-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_orders_paymet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guests', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True)),
                ('phone', models.CharField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_in_sessions', to='restaurants.table')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='dine_in_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.dineinsession'),
        ),
        migrations.AddConstraint(
            model_name='dineinsession',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table'), name='unique_active_dine_in_session_per_table'),
        ),
    ]
