# Generated by Django 5.2.9 on 2025-12-20 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_dineinsession_orders_dine_in_session_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dineinsession',
            name='unique_active_dine_in_session_per_table',
        ),
        migrations.RenameField(
            model_name='dineinsession',
            old_name='created_at',
            new_name='opened_at',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='paymet_status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='dineinsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dineinsession',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dineinsession',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dineinsession',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dineinsession',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='dineinsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('restaurant', 'table'), name='unique_active_dine_in_session_per_table'),
        ),
    ]
