# Generated by Django 5.2.9 on 2025-12-21 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_remove_dineinsession_unique_active_dine_in_session_per_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
        migrations.AddField(
            model_name='review',
            name='review_by',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Waiter')], default=1),
        ),
        migrations.AlterField(
            model_name='dineinsession',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurants.menuitem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'To Prepare'), (2, 'Preparing'), (3, 'Prepared'), (4, 'Served')], default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dine In'), (2, 'Takeaway'), (3, 'Delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cash on delivery'), (2, 'Transfer')], default=1),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Completed'), (5, 'No Show')], default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empty'), (2, 'Reserved'), (3, 'Occupied'), (4, 'Order Placed'), (5, 'Preparing Order'), (6, 'Ready to Serve'), (7, 'Served'), (8, 'Awaiting Payment'), (9, 'Cleaning'), (10, 'Unavailable')], default=1),
        ),
    ]
