# Generated by Django 5.2.9 on 2025-12-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_remove_review_created_by_review_review_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='restaurants.menuitem'),
        ),
    ]
