# Generated by Django 5.2.9 on 2025-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_alter_cartitem_menu_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dineinsession',
            name='unique_active_dine_in_session_per_table',
        ),
        migrations.AddConstraint(
            model_name='dineinsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('restaurant', 'table'), name='unique_active_dine_in_session_per_table'),
        ),
    ]
