# Generated by Django 5.2.9 on 2026-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_table_is_active'),
        ('userprofile', '0002_userprofile_avg_rating_userprofile_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='accepted_by_waiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='assigned_chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_orders', to='userprofile.userprofile'),
        ),
    ]
