# Generated by Django 5.2.17 on 2026-10-01 20:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_merge_0012_paymentdetails_cash_custody_0022_orders_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_at_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COGS per unit at the time order was prepared.', max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Idempotency flag: True if recipe inventory consumption has been deducted for this order.'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Cost of Goods Sold (COGS) for all prepared recipe items in this order.', max_digits=12),
        ),
    ]
