# Generated by Django 5.2.17 on 2026-10-01 20:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0024_orderitem_unit_cost_at_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yield_servings', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Standard number of menu portions produced by this recipe batch.', max_digits=6)),
                ('instructions', models.TextField(blank=True, default='', help_text='Culinary preparation steps for kitchen staff.')),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, order consumption is bypassed.')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurants.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'recipe_headers',
                'ordering': ['menu_item__name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text='Required raw ingredient quantity for this recipe batch.', max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.inventoryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.recipe')),
                ('uom', models.ForeignKey(blank=True, help_text="Unit of measure for this recipe line. Defaults to inventory item's UOM if blank.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Recipe Item',
                'verbose_name_plural': 'Recipe Items',
                'db_table': 'recipe_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['restaurant', 'is_active'], name='recipe_head_restaur_e22b26_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['restaurant', 'menu_item'], name='recipe_head_restaur_f9319d_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('restaurant', 'menu_item'), name='unique_recipe_per_menu_item'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['recipe', 'inventory_item'], name='recipe_item_recipe__303a2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'inventory_item'), name='unique_inventory_item_per_recipe'),
        ),
    ]
