# Generated by Django 5.2.9 on 2026-10-01 18:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0023_merge_0012_paymentdetails_cash_custody_0022_orders_fields'),
        ('userprofile', '0002_userprofile_avg_rating_userprofile_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit code. Automatically generated if left blank.', max_length=64, null=True)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('min_reorder_level', models.DecimalField(decimal_places=3, default=Decimal('5.000'), help_text='Threshold below which the item is flagged as Low Stock.', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted average or standard cost per unit.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.PositiveSmallIntegerField(choices=[(1, 'Adjustment'), (2, 'Purchase In'), (3, 'Order Consumption'), (4, 'Wastage'), (5, 'Purchase Return')], db_index=True, default=1)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Positive for stock additions, negative for reductions/consumption.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, help_text='Snapshot of the item current_stock immediately after this movement.', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost of the item at the time of movement.', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value affected (|quantity_delta| * unit_cost).', max_digits=12)),
                ('reference_note', models.CharField(blank=True, help_text="Audit explanation, e.g. 'Opening Stock Initial Count', 'Physical Audit Adjustment'.", max_length=255, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_logs', to='inventory.inventoryitem')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_stock_movements', to='userprofile.userprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_logs', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Stock Movement Log',
                'verbose_name_plural': 'Stock Movement Logs',
                'db_table': 'inventory_stock_movement_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplier to convert this unit to its base unit (e.g., 1 kg = 1000 g -> factor=1000).', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='inventory.unitofmeasure')),
                ('restaurant', models.ForeignKey(blank=True, help_text='Null restaurant indicates a system-default template unit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'inventory_units_of_measure',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_inventory_category_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['restaurant', 'inventory_item', 'created_at'], name='inventory_s_restaur_8104aa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovementlog',
            index=models.Index(fields=['restaurant', 'movement_type', 'created_at'], name='inventory_s_restaur_5197b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('restaurant', 'short_code'), name='unique_unit_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'is_active'], name='inventory_i_restaur_9e772f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'category'], name='inventory_i_restaur_689952_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_inventory_item_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False), models.Q(('sku', ''), _negated=True)), fields=('restaurant', 'sku'), name='unique_inventory_item_sku_per_restaurant'),
        ),
    ]
