# Generated by Django 5.2.17 on 2026-10-01 21:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0024_orderitem_unit_cost_at_order_and_more'),
        ('userprofile', '0002_userprofile_avg_rating_userprofile_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementlog',
            name='quantity_delta',
            field=models.DecimalField(decimal_places=3, help_text='Positive for stock additions, negative for reductions/consumption/wastage.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovementlog',
            name='reference_note',
            field=models.CharField(blank=True, help_text="Audit explanation, e.g. 'Opening Stock Initial Count', 'WASTAGE (Expired Stock)', 'Physical Audit Adjustment'.", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StockWastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of item discarded/wasted in the specified UOM.', max_digits=12)),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Expired Stock'), (2, 'Spoiled / Rotten'), (3, 'Damaged in Handling'), (4, 'Preparation Loss / Trimming'), (5, 'Overproduction / Unsold Prepared'), (6, 'Spillage / Dropped'), (7, 'Theft / Unaccounted Loss'), (8, 'Quality Issue / Rejected'), (9, 'Other Operational Loss')], db_index=True, default=1, help_text='Categorized operational reason for the wastage.')),
                ('notes', models.TextField(blank=True, default='', help_text='Contextual details, lot numbers, or incident explanation.')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost basis (WAC) at the time of wastage.', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total financial loss (quantity * unit_cost).', max_digits=12)),
                ('wastage_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date when wastage occurred or was identified.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_wastages', to='userprofile.userprofile')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_records', to='inventory.inventoryitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_wastage_records', to='restaurants.restaurant')),
                ('uom', models.ForeignKey(blank=True, help_text='Unit of measure for the recorded quantity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_records', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Stock Wastage',
                'verbose_name_plural': 'Stock Wastages',
                'db_table': 'inventory_stock_wastage',
                'ordering': ['-wastage_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovementlog',
            name='wastage',
            field=models.ForeignKey(blank=True, help_text='Direct link to the originating StockWastage record if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_logs', to='inventory.stockwastage'),
        ),
        migrations.AddIndex(
            model_name='stockwastage',
            index=models.Index(fields=['restaurant', 'wastage_date'], name='inventory_s_restaur_a6856d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockwastage',
            index=models.Index(fields=['restaurant', 'reason'], name='inventory_s_restaur_34c6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockwastage',
            index=models.Index(fields=['restaurant', 'inventory_item'], name='inventory_s_restaur_d257d0_idx'),
        ),
    ]
