# Generated by Django 5.2.17 on 2026-10-01 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0023_merge_0012_paymentdetails_cash_custody_0022_orders_fields'),
        ('userprofile', '0002_userprofile_avg_rating_userprofile_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'purchase_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_number', models.CharField(help_text='Restaurant-unique purchase identifier, e.g. PO-000001', max_length=64)),
                ('invoice_number', models.CharField(blank=True, default='', help_text="Supplier's physical or electronic tax invoice reference", max_length=128)),
                ('purchase_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Received'), (3, 'Cancelled')], db_index=True, default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated sum of all line item totals', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Applicable sales tax or VAT', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final gross payable: subtotal + tax_amount', max_digits=12)),
                ('receipt_image', models.ImageField(blank=True, help_text='Scan or photo of paper receipt / supplier delivery challan', null=True, upload_to='purchases/receipts/')),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to='userprofile.userprofile')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_orders', to='userprofile.userprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='restaurants.restaurant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_orders',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text="Purchased quantity in item's base Unit of Measure", max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Agreed purchase cost per unit (excluding tax)', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Calculated line total: quantity * unit_cost', max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'purchase_order_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['purchase_order', 'inventory_item'], name='purchase_or_purchas_1180cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('purchase_order', 'inventory_item'), name='unique_item_per_purchase_order')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['restaurant', 'is_active'], name='purchase_su_restaur_522dbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_supplier_name_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['restaurant', 'status', 'purchase_date'], name='purchase_or_restaur_88d3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['restaurant', 'supplier'], name='purchase_or_restaur_b1004f_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('restaurant', 'purchase_number'), name='unique_purchase_number_per_restaurant'),
        ),
    ]
