# Generated by Django 5.2.17 on 2026-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_number',
            field=models.CharField(blank=True, help_text='Restaurant-unique purchase identifier, e.g. PO-000001', max_length=64),
        ),
    ]
